version: '3.9' # Define a versão do formato do arquivo Docker Compose

services:
  sistemacorp: # Nome da Aplicação
    build: # Configuração para construir a imagem do Docker
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python -Xutf8 manage.py loaddata /scripts/sistema.fixture.json &&
            python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000 # Mapeia a porta 8000 do contêiner para a porta 8000 do host
    volumes: # Monta volumes incluindo arquivos estáticos e de mídia do Django.
      - ./data/web:/vol/web
      - ./SistemaCorp:/SistemaCorp
      - ./SistemaCorp/media:/vol/web/media
    env_file:
      - sistema.env # como usar o .env no docker-compose
    environment: # Define variáveis de ambiente diretamente
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - POSTGRES_HOST=db
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    depends_on:
      - db

  db: # Usa a imagem oficial do PostgreSQL versão 13 no Alpine Linux
    image: postgres:13-alpine
    env_file:
      - sistema.env # como usar o .env no docker-compose
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme